services:
  ustat:
    build: .
    container_name: ustat
    volumes:
      - ./headers.txt:/app/headers.txt
      # - .:/app
      # - /app/node_modules # Prevent local node_modules override
    command: bun run start
    restart: unless-stopped
